<?php
print "AAAAAA $urlsito";
$img_plus="$urlsito/img/plus.gif";
$img_minus="$urlsito/img/minus.gif";
$img_lastlink="$urlsito/img/lastlink.gif";
$img_link="$urlsito/img/link.gif";
$img_cube="$urlsito/img/cube.gif";
$img_dim="$urlsito/img/dimension2.gif";
$img_hier="$urlsito/img/hierarchy.gif";
$img_lev="$urlsito/img/level.gif";
$img_prop="$urlsito/img/property.gif";
$img_mea="$urlsito/img/measure.gif";
$img_del="$urlsito/img/delete.png";
$img_arrdown="$urlsito/img/arrow_down.png";
$img_arrup="$urlsito/img/arrow_up.png";
$img_sortasc="$urlsito/img/sort_ascend.png";
$img_sortdesc="$urlsito/img/sort_descend.png";
$img_save="$urlsito/img/save.png";
$img_back="$urlsito/img/back.png";
$img_pdf="$urlsito/img/pdf.png";
$img_home="$urlsito/img/home.png";
$img_new="$urlsito/img/new.png";
$img_open="$urlsito/img/open.png";
$img_csv="$urlsito/img/csv.png";
$img_fb="$urlsito/img/fb.png";
$img_share="$urlsito/img/share.png";
$img_tw="$urlsito/img/twitter.png";
$img_report="$urlsito/img/report.png";
$img_email="$urlsito/img/email.png";
$img_linkedin="$urlsito/img/linkedin.png";
$img_google="$urlsito/img/google.png";
$img_weka="$urlsito/img/weka.jpg";

?>
